version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
    - 5432:5432
    volumes:
    - ./docker/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: example
